experiment_series: DLDLM_interactive_evaluation
experiment_id: small_emp_chitchat
experiments_directory_path: ./experiments/

random_seed: 2307
mixed_precision: true

dldlm:
  model:
    pretrained: &pretrained ./resources/models/dldlm-small-emp/
    max_context_len: 256
    generation_kwargs:
      num_beams: 4
      do_sample: true
      max_length: 1024
      min_length: 1
      top_p: 0.8
  tokeniser:
    pretrained: *pretrained

log_level: ERROR
log_file: true
