experiment_series: DLDLM_ablations
experiment_id: dldlm_distilled_threshold_cdrop_tf_corrupt
experiments_directory_path: ./experiments/

random_seed: 2307
mixed_precision: true

dldlm:
  model:
    pretrained: &pretrained distilgpt2
    kwargs:
      n_styles: &n_styles 8
      tf_size: 50256
      latent_loss_threshold: 2.0
    generate_kwargs:
      max_length: 384
      min_length: 1
      do_sample: true
      top_p: 1.
      top_k: 0
      temperature: 0.7
  tokeniser:
    pretrained: *pretrained
    n_styles: *n_styles

optimizer:
  kwargs:
    lr: &lr 5.e-5
  n_epochs: 15
  max_gradient_norm: 1.0

lr_scheduler:
  lr_start: *lr
  lr_stop: *lr
  warmup: 0

beta_scheduler:
  warmup: 0
  cycles: 0

evaluation:
  validation_period: 2048
  monitored_metric: elbo
  metrics:
    word_count:
      top_n: 20
    traces:
      window_size: 4
    sample_responses:
      n_samples: 5

data:
  corpora_dir_path: ./resources/data/raw/
  cache_dir_path: ./resources/data/cache/
  kwargs:
    corpus_list:
      - dailydialog
      - empatheticdialogues
      - personachat
      - wizard_of_wikipedia
    max_context_length: 256
    max_response_length: 128
    count_word_tokens: true
  splits:
    train:
      mini_batch_size: 64
      in_mem: 8
      n_workers: &n_workers 4
    validation:
      mini_batch_size: &eval_mini_batch_size 64
      in_mem: *eval_mini_batch_size
      n_workers: *n_workers
    test:
      mini_batch_size: *eval_mini_batch_size
      in_mem: *eval_mini_batch_size
      n_workers: *n_workers

log_level: DEBUG
log_file: true
