experiment_series: DLDLM_pretraining
experiment_id: dldlm_medium
experiments_directory_path: ./experiments/

random_seed: 2307
mixed_precision: true

dldlm:
  model:
    pretrained: &pretrained gpt2-medium
    kwargs:
      n_styles: &n_styles 8
      tf_size: 50256
      init_tf_head: false
      context_pdrop: 0.0
      corruption_rate: 0.0
      # do_gibbs_sampling: true
      kl_loss: false
      behaviour_loss: true
      sampling_loss: true
      behaviour_loss_weight: 0.001
      # prior_entropy_loss: true
      # posterior_entropy_loss: true
      # prior_entropy_loss_weight: -0.1
      tf_loss: false
    generate_kwargs:
      max_length: 384
      min_length: 1
      do_sample: true
      top_p: 0.8
      top_k: 0
      temperature: 1.
  tokeniser:
    pretrained: *pretrained
    n_styles: *n_styles

optimizer:
  kwargs:
    lr: &lr 1.e-6
  n_epochs: 10
  max_gradient_norm: 1.0

lr_scheduler:
  lr_start: *lr
  lr_stop: *lr
  warmup: 0

beta_scheduler:
  cycles: 0
  warmup: 0

evaluation:
  validation_period: 2048
  monitored_metric: prior_latent_nll_loss
  metrics:
    word_count:
      top_n: 20
    traces:
      window_size: 4
    sample_responses:
      n_samples: 5

data:
  corpora_dir_path: ./resources/data/raw/
  cache_dir_path: ./resources/data/cache/
  kwargs:
    corpus_list:
      - dailydialog
      - empatheticdialogues
      - personachat
      - wizard_of_wikipedia
    max_context_length: 256
    max_response_length: 128
    count_word_tokens: true
  splits:
    train:
      mini_batch_size: 64
      in_mem: 4
      n_workers: &n_workers 4
    validation:
      mini_batch_size: &eval_mini_batch_size 16
      in_mem: *eval_mini_batch_size
      n_workers: *n_workers
    test:
      mini_batch_size: *eval_mini_batch_size
      in_mem: *eval_mini_batch_size
      n_workers: *n_workers

log_level: DEBUG
log_file: true
